Some additional fixes to salix-update-notifier

diff --git a/system/salix-update-notifier/remove_zenity.patch b/system/salix-update-notifier/remove_zenity.patch
--- a/system/salix-update-notifier/remove_zenity.patch
+++ b/system/salix-update-notifier/remove_zenity.patch
@@ -1,6 +1,13 @@
 --- src/salix-update-notifier	2016-08-07 18:28:06.000000000 -0400
-+++ src/salix-update-notifier.new	2018-11-29 23:25:38.757736216 -0500
-@@ -25,12 +25,6 @@
++++ src/salix-update-notifier.new	2018-12-02 21:48:51.770206662 -0500
+@@ -19,31 +19,20 @@
+ elif [[ `which ktsuss 2> /dev/null` ]]; then
+ 	SUCOMMAND="ktsuss -u root"
+ elif [[ `which kdesu 2> /dev/null` ]]; then
+-	SUCOMMAND="kdesu"
++	SUCOMMAND="kdesu -c"
+ else
+ 	echo "`eval_gettext 'ERROR: gksu, ktsuss or kdesu are required for salix-update-notifier to work.'`" >&2
  	exit 1
  fi
  
@@ -10,10 +17,10 @@
 -	exit 1
 -fi
 -
- # Wait 10 mins before running for the first time
- sleep 10m
- 
-@@ -38,12 +32,7 @@
+-# Wait 10 mins before running for the first time
+-sleep 10m
+-
+ # Main loop
  while true; do
  	if [[ `LANG=C /usr/sbin/slapt-get -s --upgrade | grep "Need to get"` ]]
  	then
@@ -23,7 +30,10 @@
 -		--text="`eval_gettext 'Package updates are available for your system.\n\nSelecting OK will perform the updates using gslapt. Root user privileges will be required in order to do that.\n\nProceed with updating?'`" \
 -		--window-icon=/usr/share/pixmaps/salix-update-notifier.png \
 -		&& $SUCOMMAND gslapt --upgrade
-+		/usr/libexec/salix-update-notifier-tray-icon && $SUCOMMAND gslapt --upgrade
++		/usr/libexec/salix-update-notifier-tray-icon
++		if [ $? -eq 0 ]; then
++			$SUCOMMAND "gslapt --upgrade"
++		fi
  	fi
  
  	# Check if there is a config file that sets a different interval
